.Dd May 11, 2017
.Dt WD 1
.Os

.Sh NAME
.Nm wd
.Nd find the weekday of a date

.Sh SYNOPSIS
.Nm
.Op Ar dates

.Sh DESCRIPTION
.Nm
takes dates and prints their weekdays. If wd is called without any
arguments, it reads one date per line from stdin, otherwise it prints
the weekdays of the arguments.
.Pp
An argument must have the form YEAR-MONTH-DAY (all of them must be >=1).
The output has the form YEAR-MONTH-DAY:WEEKDAY.

.Sh EXAMPLES
Print the weekday of two dates:
.Pp
.Dl $ wd 2015-07-07 16777213-08-14
.Dl 2015-07-07:Tuesday
.Dl 16777213-08-14:Wedneyday

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr cal ,
.Xr date 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.de
